### ISSUE TITLE
Host Dockerfiles on Docker Hub

### ISSUE THREAD

**Issue by gbroques** [gbroques/ose-3d-printer-workbench#92]
How to abstract this:
* Host Dockerfiles on [Docker Hub](https://hub.docker.com/).
* Update `.travis.uml` accordingly See: https://docs.travis-ci.com/user/docker/ (below snippet)

* [docker-compose.yml](https://github.com/gbroques/ose-3d-printer-workbench/blob/master/docker-compose.yml)
* [docs.Dockerfile](https://github.com/gbroques/ose-3d-printer-workbench/blob/master/docs.Dockerfile)
* [test.Dockerfile](https://github.com/gbroques/ose-3d-printer-workbench/blob/master/test.Dockerfile)

```yml
language: ruby

services:
  - docker

before_install:
  - docker build -t carlad/sinatra .
```

**TODO:** Create base test image that's repo agnostic.

Then extend it.
